version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run: chmod a+x ./deploy.sh
      - run: ./deploy.sh
    branches:
      only:
        - master
